name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up CMake
      uses: actions/setup-cmake@v1
    - name: Build
      run: |
        mkdir -p build
        cmake -B ./build/
        cmake --build ./build --target Kup -j 10
    - name: Run
      run: ./build/Kup
