name: MSYS2
on: [push, pull_request]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc

      - name: install-cmake
        uses: Symbitic/install-cmake@v0.1.0
        with:
    # Version of CMake to install
          cmake: 3.29
    # Version of ninja-build to install
          ninja: 1.9.0
      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=ninja -G Ninja -S . -B ./cmake-build-debug
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          ./ci-build.sh
